In [43]:
import pytest
import pandas as pd
import scipy.stats as stats
from sklearn.metrics import (confusion_matrix,
                             precision_score,
                             average_precision_score,
                             recall_score,
                             f1_score,
                             accuracy_score, # fraction of correct predictions
                             balanced_accuracy_score, # avoids inflated accuracy scores
                                                      # for imbalanced datasets
                                                      # by weighting each class equally.
                                                      # AKA "informedness"
                             roc_auc_score,
                             roc_curve,
                             fbeta_score,
                             jaccard_score,
                             hinge_loss,
                             log_loss,
                             matthews_corrcoef, 
                             precision_recall_curve, # precision-recall pairs for different probability thresholds
                             class_likelihood_ratios,# binary classification positive and negative likelihood ratios
                             hamming_loss,
                             zero_one_loss)

In [31]:
%run ../binary_chi2_test.py

In [8]:
df = pd.read_parquet('../../data/cancer.parquet')
df['big_radius'] = (df.mean_radius > df.mean_radius.mean()).astype(int)
df.head()

has_cancer  mean_radius  mean_texture  mean_perimeter  mean_area  \
0           1        17.99         10.38          122.80     1001.0   
1           1        20.57         17.77          132.90     1326.0   
2           1        19.69         21.25          130.00     1203.0   
3           1        11.42         20.38           77.58      386.1   
4           1        20.29         14.34          135.10     1297.0   

   mean_smoothness  mean_compactness  mean_concavity  mean_concave_points  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   mean_symmetry  ...  worst_texture  worst_perimeter  worst_area  \
0         0.2419  ...          17.33           184.60      2019.0   
1         0.1812  ...          23.41           158.80      1956.0   
2         0.2069  ...          25.53           152.50      1709.0   
3         0.2597  ...          26.50            98.87       567.7   
4         0.1809  ...          16.67           152.20      1575.0   

   worst_smoothness  worst_compactness  worst_concavity  worst_concave_points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst_symmetry  worst_fractal_dimension  big_radius  
0          0.4601                  0.11890           1  
1          0.2750                  0.08902           1  
2          0.3613                  0.08758           1  
3          0.6638                  0.17300           0  
4          0.2364                  0.07678           1  

[5 rows x 32 columns]

In [22]:
target, feature = df['has_cancer'], df['big_radius']

In [32]:
binary_chi2_test(target, feature)

285.1548

In [33]:
binary_chi2_p_value(target, feature)

0.0

In [35]:
binary_chi2_hypothesis_test(target, feature).values

array([[0.001, 285.1548, 0.0, True],
       [0.01, 285.1548, 0.0, True],
       [0.05, 285.1548, 0.0, True],
       [0.1, 285.1548, 0.0, True],
       [0.2, 285.1548, 0.0, True],
       [0.25, 285.1548, 0.0, True],
       [0.5, 285.1548, 0.0, True]], dtype=object)

In [44]:
p, r, th = precision_recall_curve(target, feature)

In [50]:
p

array([0.37258348, 0.79646018, 1.        ])

In [51]:
r

array([1.       , 0.8490566, 0.       ])

In [49]:
np.diff(r)

array([-0.1509434, -0.8490566])

In [52]:
average_precision_score(target, feature)

0.7324787887342377

In [42]:
fpr, tpr, thresholds = roc_curve(target, feature)
roc_auc_score(target, feature, 4)

TypeError: too many positional arguments

In [41]:
thresholds

array([inf,  1.,  0.])

In [27]:
expected

array([[215.20386643, 141.79613357],
       [127.79613357,  84.20386643]])

In [12]:
binary_pb_correlation_test(df.has_cancer, df.big_radius)

0.7116343928969042

In [20]:
binary_pb_correlation_hypothesis_test(df.has_cancer, df.big_radius).values

array([[0.001, 0.7116343928969042, 5.469535799564555e-89, True],
       [0.01, 0.7116343928969042, 5.469535799564555e-89, True],
       [0.05, 0.7116343928969042, 5.469535799564555e-89, True],
       [0.1, 0.7116343928969042, 5.469535799564555e-89, True],
       [0.2, 0.7116343928969042, 5.469535799564555e-89, True],
       [0.25, 0.7116343928969042, 5.469535799564555e-89, True],
       [0.5, 0.7116343928969042, 5.469535799564555e-89, True]],
      dtype=object)

big_radius    0    1
has_cancer          
0           311   46
1            32  180